---
apiVersion: v1
kind: Namespace
metadata:
  name: speedire

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-world-service
#   namespace: speedire
# spec:
#   selector:
#     app: hello-world
#   ports:
#     - protocol: TCP
#       port: 9090
#       targetPort: 8000
#   type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: speedire
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: speedireexample:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000